services:
  mysql:
    image: mysql:8.4
    container_name: insurance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insurance
      MYSQL_USER: insurance
      MYSQL_PASSWORD: insurance
    ports:
      - "3306:3306"
    volumes:
      - insurance-mysql-data:/var/lib/mysql

volumes:
  insurance-mysql-data:
