classDiagram
direction TB
class Review {
  <<abstract>>
  Long id
  ReviewResult result
}
class EnrollmentReview
class BenefitPaymentReview
Review <|-- EnrollmentReview
Review <|-- BenefitPaymentReview
